import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://mvw-stage.iihdev.com/');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'your@email.com' }).fill('superadmin@yopmail.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Superadmin@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Brands' }).click();
  await page.getByRole('button', { name: 'Add Brand' }).click();
  await page.getByRole('textbox', { name: 'Enter brand name' }).click();
  await page.getByRole('textbox', { name: 'Enter brand name' }).fill('Xiaomi');
  await page.getByRole('textbox', { name: 'Enter model' }).click();
  await page.getByRole('textbox', { name: 'Enter model' }).fill('10');
  await page.getByRole('textbox', { name: 'Enter year or range' }).click();
  await page.getByRole('textbox', { name: 'Enter year or range' }).fill('2010');
  await page.getByRole('textbox', { name: 'Enter length' }).click();
  await page.getByRole('textbox', { name: 'Enter length' }).fill('30');
  await page.getByRole('textbox', { name: 'Enter roof height' }).click();
  await page.getByRole('textbox', { name: 'Enter roof height' }).fill('20');
  await page.locator("div[class='flex flex-col items-center gap-1.5 text-muted-foreground ']").setInputFiles('/home/user/Documents/Test data/1MB_JPG.jpg');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('link', { name: 'Templates' }).click();
  await page.getByRole('button', { name: 'Add Template' }).click();
  await page.getByRole('button', { name: 'Select Brand ▼' }).click();
  await page.getByRole('menuitem', { name: 'Soe' }).click();
  await page.getByRole('button', { name: 'Select Model ▼' }).click();
  await page.getByRole('menuitem', { name: '10' }).click();
  await page.getByRole('button', { name: 'Select Year ▼' }).click();
  await page.getByRole('menuitem', { name: '2010' }).click();
  await page.getByRole('button', { name: 'Select Length ▼' }).click();  
  await page.getByRole('menuitem', { name: '30' }).click();
  await page.getByRole('button', { name: 'Select Roof Height ▼' }).click();
  await page.getByRole('menuitem', { name: '20' }).click();
  await page.getByRole('button', { name: 'Select variant ▼' }).click();
  await page.getByRole('menuitem', { name: 'Full Kit' }).click();
  await page.getByRole('textbox', { name: 'Template Price *' }).click();
  await page.getByRole('textbox', { name: 'Template Price *' }).fill('299');
  //await page.getByText('Drop PDF files here.pdf').click();
  await page.locator('div.flex.flex-col.items-center.gap-1\.5.text-muted-foreground').setInputFiles('/home/user/Documents/Test data/3MB_PDF.pdf');
  await page.getByRole('button', { name: 'Add Template' }).click();
  await page.getByRole('link', { name: 'Customers' }).click();
  await page.getByRole('link', { name: 'Orders' }).click();
  await page.getByRole('button', { name: 'S Super Admin superadmin@' }).click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
});